//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebAPI_ModelContainer : DbContext
    {
        public WebAPI_ModelContainer()
            : base("name=WebAPI_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyTable> MyTables { get; set; }
        public virtual DbSet<MyView> MyViews { get; set; }
    
        public virtual ObjectResult<MyProcedure_Result> MyProcedure(Nullable<int> myID, string myFirstName)
        {
            var myIDParameter = myID.HasValue ?
                new ObjectParameter("MyID", myID) :
                new ObjectParameter("MyID", typeof(int));
    
            var myFirstNameParameter = myFirstName != null ?
                new ObjectParameter("MyFirstName", myFirstName) :
                new ObjectParameter("MyFirstName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyProcedure_Result>("MyProcedure", myIDParameter, myFirstNameParameter);
        }
    }
}
